<script setup lang="ts">
import { computed, ref } from 'vue'
import { stages, type Goal } from './data/builds'
import raw from './data/ore-data.json'
type Raw={rarity:string;chances:string;url:string}; type Spot={location:string;chance:number;odds:string}
const ores=Object.entries(raw as Record<string,Raw>).map(([name,d])=>{const all=d.chances.split('\n').map(line=>{const m=line.match(/^(.*?)\s[-–]\s([\d.]+)%\s\((.*?)\)$/);return m?{location:m[1],chance:+m[2],odds:m[3]}:null}).filter((x):x is Spot=>!!x);const normal=all.filter(x=>!x.location.startsWith('The Void'));const spots=(normal.length?normal:all).sort((a,b)=>b.chance-a.chance).slice(0,3);const p=(spots[0]?.chance||0)/100;return{name,rarity:d.rarity,spots,voidSpot:all.find(x=>x.location.startsWith('The Void')),luck:p?Math.max(1,Math.ceil(Math.log(.5)/Math.log(1-p))):0,url:d.url}}).sort((a,b)=>a.name.localeCompare(b.name))
const view=ref<'builds'|'ores'>('builds'),stageIndex=ref(0),goal=ref<Goal>('luck'),filter=ref(''),oreQuery=ref(''),selected=ref(ores.find(x=>x.name==='Dinosaur Skull')||ores[0])
const stage=computed(()=>stages[stageIndex.value]),build=computed(()=>stage.value.builds[goal.value])
const museum=computed(()=>Object.entries(build.value.museum).map(([r,a])=>[r,a.filter(x=>x.toLowerCase().includes(filter.value.toLowerCase()))] as [string,string[]]).filter(([,a])=>a.length))
const results=computed(()=>ores.filter(x=>x.name.toLowerCase().includes(oreQuery.value.toLowerCase())))
function openOre(label:string){const found=ores.find(o=>label.toLowerCase().includes(o.name.toLowerCase()));if(found){selected.value=found;oreQuery.value=found.name}view.value='ores';scrollTo({top:0,behavior:'smooth'})}
</script>

<template><main><header><button class="brand" @click="view='builds'"><i>⛏</i><span><b>PROSPECTOR</b><small>Build Field Guide</small></span></button><nav><button :class="{active:view==='builds'}" @click="view='builds'">Builds</button><button :class="{active:view==='ores'}" @click="view='ores'">⌕ Ore Finder</button></nav></header>
<section v-if="view==='ores'" class="finder"><button class="back" @click="view='builds'">← Back to builds</button><p class="eyebrow">51 museum ores indexed</p><h1>Where should I farm this ore?</h1><p class="muted">Search an ore to compare its three highest base-chance locations.</p><div class="finder-grid"><aside class="panel"><input v-model="oreQuery" placeholder="Try: Dinosaur Skull"><div class="results"><button v-for="o in results" :key="o.name" :class="{active:selected.name===o.name}" @click="selected=o"><span><b>{{o.name}}</b><small>{{o.rarity}}</small></span><em>{{o.spots[0]?.chance.toPrecision(3)}}%</em></button></div></aside><article class="panel detail"><div class="detail-head"><div><span class="rarity" :class="selected.rarity.toLowerCase()">{{selected.rarity}}</span><h2>{{selected.name}}</h2></div><a :href="selected.url" target="_blank">Open Wiki ↗</a></div><div class="metrics"><div><small>Recommended Luck</small><b>{{selected.luck.toLocaleString()}}+</b><span>≈ 50% cumulative target</span></div><div><small>Best base chance</small><b>{{selected.spots[0]?.chance.toPrecision(4)}}%</b><span>{{selected.spots[0]?.odds}}</span></div></div><h3>Top farming locations</h3><div class="spots"><div v-for="(s,i) in selected.spots" :key="s.location"><i>{{i+1}}</i><span><b>{{s.location}}</b><small>{{s.odds}}</small></span><strong>{{s.chance.toPrecision(4)}}%</strong></div></div><div v-if="selected.voidSpot" class="void"><b>Void chance</b><p>{{selected.voidSpot.chance.toPrecision(4)}}% · {{selected.voidSpot.odds}}. Only when this ore is in the Void loot pool.</p></div><div class="note"><b>Luck estimate</b><p>Calculated from the Wiki's reroll mechanic for an approximate 50% cumulative chance. Some ores can weaken or ignore Luck, so this is a comparison target—not a guarantee.</p></div></article></div></section>
<div v-else class="layout"><aside class="stages"><p>CHOOSE STAGE</p><button v-for="(s,i) in stages" :key="s.name" :class="{active:i===stageIndex}" @click="stageIndex=i"><b>{{s.name}}</b><small>{{s.area}}</small></button></aside><section class="content"><div v-if="stageIndex===0" class="path"><b>YOUR RECOMMENDED PATH</b><h3>Snow unlocked → rebuild in Caldera first</h3><p>Get the Caldera core below, then enter Snow without wasting resources.</p></div><p class="eyebrow">{{stage.name}}</p><h1>{{stage.area}}</h1><div class="goals"><button v-for="g in ['luck','size','sell'] as Goal[]" :key="g" :class="{active:goal===g}" @click="goal=g"><b>{{g}}</b><small>{{g==='luck'?'Rarer ores & progression':g==='size'?'Big ores & museum':'Swap before selling'}}</small></button></div><div class="panel use"><b>{{goal.toUpperCase()}} USE CASE</b><p>{{build.use}}</p><small>STAT PRIORITY</small><strong>{{build.priority}}</strong></div><div class="build-grid"><div><section class="panel"><h3>Equipment loadout</h3><dl><template v-for="([k,v]) in [['Charm',build.charm],['Neck',build.neck],['Rings',build.rings],['Runes',build.runes],['Pan',build.pan],['Shovel',build.shovel]]" :key="k"><dt>{{k}}</dt><dd><template v-if="Array.isArray(v)"><span v-for="x in v" :key="x">{{x}}</span></template><template v-else>{{v}}</template></dd></template></dl></section><section class="panel tips"><h3>Before you farm</h3><p v-for="n in build.notes" :key="n">✓ {{n}}</p></section></div><section class="panel"><div class="museum-head"><div><h3>Museum build</h3><p>Click an ore to see where to farm it.</p></div><input v-model="filter" placeholder="Filter build"></div><div v-for="([r,items]) in museum" :key="r" class="museum-row"><span class="rarity" :class="r.toLowerCase()">{{r}}</span><div><button v-for="x in items" :key="x" @click="openOre(x)">{{x}} ⌖</button></div></div></section></div></section></div></main></template>
